[package]
name = "diffable"
version = "0.5.1"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "a differential geometry framework for rust"
readme = "readme.md"
homepage = "https://aaroncottle.au"
repository = "https://github.com/minerscale/diffable"
keywords = ["mathematics", "geometry", "linear-algebra", "abstract-algebra", "topology"]
categories = ["mathematics", "science"]

[package.metadata.docs.rs]
all-features = true

[lib]
path = "src/lib.rs"
name = "diffable"

[features]
default = ["std", "simplicial"]
std = ["num-traits/std"]
simplicial = ["std"]
testing = ["std", "dep:proptest"]
all = ["simplicial", "testing"]

[dependencies]
num-traits = {version = "0.2.19", default-features = false, features = ["libm"]}
proptest = { version = "1.11.0", optional = true }
num-derive = "0.5.1"
